# Generated by Django 4.1 on 2022-09-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cetegory_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cetegory',
            new_name='category',
        ),
    ]
